sonar.projectKey=Digitalized-Energy-Systems_monee
sonar.organization=digitalized-energy-systems

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=monee
sonar.projectVersion=0.1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src

# Exclude the benchmark scripts and the test suite from analysis.
sonar.exclusions=benchmarks/**,tests/**,docs/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# python specifics
sonar.python.version=3.10, 3.11, 3.12, 3.13

# Test coverage path
sonar.python.coverage.reportPaths=coverage.xml
